export const SET_TRAILER_LINK = "SET_TRAILER_LINK";
export const SET_MOVIE_SCHEDULING_DETAIL = "SET_MOVIE_SCHEDULING_DETAIL";
export const SET_THEATER = "SET_THEATER";
export const SET_SCHEDULED_TIME = "SET_SCHEDULED_TIME";
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";
export const SET_SELECTED_MOVIE = "SET_SELECTED_MOVIE";
