export const SET_MOVIE_SCHEDULING_DETAIL_ST = "SET_MOVIE_SCHEDULING_DETAIL_ST";
export const SET_THEATER_ST = "SET_THEATER_ST";
export const SET_SCHEDULED_TIME_ST = "SET_SCHEDULED_TIME_ST";
export const SET_SELECTED_DATE_ST = "SET_SELECTED_DATE_ST";
export const SET_THEATER_BRAND_ST = "SET_THEATER_BRAND_ST";
